//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Solicitud.ProxyGarantia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GarantiaBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_SolicitudesCreditos")]
    [System.SerializableAttribute()]
    public partial class GarantiaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Des_garantiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Est_garantiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_ult_modField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_garantiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tip_garantiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_ult_modField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Valor_garantiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apeClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Des_garantia {
            get {
                return this.Des_garantiaField;
            }
            set {
                if ((object.ReferenceEquals(this.Des_garantiaField, value) != true)) {
                    this.Des_garantiaField = value;
                    this.RaisePropertyChanged("Des_garantia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_garantia {
            get {
                return this.Est_garantiaField;
            }
            set {
                if ((this.Est_garantiaField.Equals(value) != true)) {
                    this.Est_garantiaField = value;
                    this.RaisePropertyChanged("Est_garantia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg {
            get {
                return this.Fec_regField;
            }
            set {
                if ((this.Fec_regField.Equals(value) != true)) {
                    this.Fec_regField = value;
                    this.RaisePropertyChanged("Fec_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_ult_mod {
            get {
                return this.Fec_ult_modField;
            }
            set {
                if ((this.Fec_ult_modField.Equals(value) != true)) {
                    this.Fec_ult_modField = value;
                    this.RaisePropertyChanged("Fec_ult_mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_cli {
            get {
                return this.Id_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_cliField, value) != true)) {
                    this.Id_cliField = value;
                    this.RaisePropertyChanged("Id_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_garantia {
            get {
                return this.Id_garantiaField;
            }
            set {
                if ((this.Id_garantiaField.Equals(value) != true)) {
                    this.Id_garantiaField = value;
                    this.RaisePropertyChanged("Id_garantia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tip_garantia {
            get {
                return this.Tip_garantiaField;
            }
            set {
                if ((object.ReferenceEquals(this.Tip_garantiaField, value) != true)) {
                    this.Tip_garantiaField = value;
                    this.RaisePropertyChanged("Tip_garantia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_registro {
            get {
                return this.Usu_registroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_registroField, value) != true)) {
                    this.Usu_registroField = value;
                    this.RaisePropertyChanged("Usu_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_ult_mod {
            get {
                return this.Usu_ult_modField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_ult_modField, value) != true)) {
                    this.Usu_ult_modField = value;
                    this.RaisePropertyChanged("Usu_ult_mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Valor_garantia {
            get {
                return this.Valor_garantiaField;
            }
            set {
                if ((this.Valor_garantiaField.Equals(value) != true)) {
                    this.Valor_garantiaField = value;
                    this.RaisePropertyChanged("Valor_garantia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apeCliente {
            get {
                return this.apeClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.apeClienteField, value) != true)) {
                    this.apeClienteField = value;
                    this.RaisePropertyChanged("apeCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomCliente {
            get {
                return this.nomClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nomClienteField, value) != true)) {
                    this.nomClienteField = value;
                    this.RaisePropertyChanged("nomCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyGarantia.IServicioGarantia")]
    public interface IServicioGarantia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGarantia/InsertGarantia", ReplyAction="http://tempuri.org/IServicioGarantia/InsertGarantiaResponse")]
        bool InsertGarantia(MVC_Solicitud.ProxyGarantia.GarantiaBE objGarantiaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGarantia/InsertGarantia", ReplyAction="http://tempuri.org/IServicioGarantia/InsertGarantiaResponse")]
        System.Threading.Tasks.Task<bool> InsertGarantiaAsync(MVC_Solicitud.ProxyGarantia.GarantiaBE objGarantiaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGarantia/UpdateGarantia", ReplyAction="http://tempuri.org/IServicioGarantia/UpdateGarantiaResponse")]
        bool UpdateGarantia(MVC_Solicitud.ProxyGarantia.GarantiaBE objGarantiaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGarantia/UpdateGarantia", ReplyAction="http://tempuri.org/IServicioGarantia/UpdateGarantiaResponse")]
        System.Threading.Tasks.Task<bool> UpdateGarantiaAsync(MVC_Solicitud.ProxyGarantia.GarantiaBE objGarantiaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGarantia/DeleteGarantia", ReplyAction="http://tempuri.org/IServicioGarantia/DeleteGarantiaResponse")]
        bool DeleteGarantia(int Id_garantia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGarantia/DeleteGarantia", ReplyAction="http://tempuri.org/IServicioGarantia/DeleteGarantiaResponse")]
        System.Threading.Tasks.Task<bool> DeleteGarantiaAsync(int Id_garantia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGarantia/GetGarantiaPorCliente", ReplyAction="http://tempuri.org/IServicioGarantia/GetGarantiaPorClienteResponse")]
        MVC_Solicitud.ProxyGarantia.GarantiaBE GetGarantiaPorCliente(string Id_cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGarantia/GetGarantiaPorCliente", ReplyAction="http://tempuri.org/IServicioGarantia/GetGarantiaPorClienteResponse")]
        System.Threading.Tasks.Task<MVC_Solicitud.ProxyGarantia.GarantiaBE> GetGarantiaPorClienteAsync(string Id_cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGarantia/GetGarantia", ReplyAction="http://tempuri.org/IServicioGarantia/GetGarantiaResponse")]
        MVC_Solicitud.ProxyGarantia.GarantiaBE GetGarantia(int Id_garantia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGarantia/GetGarantia", ReplyAction="http://tempuri.org/IServicioGarantia/GetGarantiaResponse")]
        System.Threading.Tasks.Task<MVC_Solicitud.ProxyGarantia.GarantiaBE> GetGarantiaAsync(int Id_garantia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGarantia/GetAllGarantias", ReplyAction="http://tempuri.org/IServicioGarantia/GetAllGarantiasResponse")]
        MVC_Solicitud.ProxyGarantia.GarantiaBE[] GetAllGarantias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGarantia/GetAllGarantias", ReplyAction="http://tempuri.org/IServicioGarantia/GetAllGarantiasResponse")]
        System.Threading.Tasks.Task<MVC_Solicitud.ProxyGarantia.GarantiaBE[]> GetAllGarantiasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioGarantiaChannel : MVC_Solicitud.ProxyGarantia.IServicioGarantia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGarantiaClient : System.ServiceModel.ClientBase<MVC_Solicitud.ProxyGarantia.IServicioGarantia>, MVC_Solicitud.ProxyGarantia.IServicioGarantia {
        
        public ServicioGarantiaClient() {
        }
        
        public ServicioGarantiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGarantiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGarantiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGarantiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertGarantia(MVC_Solicitud.ProxyGarantia.GarantiaBE objGarantiaBE) {
            return base.Channel.InsertGarantia(objGarantiaBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertGarantiaAsync(MVC_Solicitud.ProxyGarantia.GarantiaBE objGarantiaBE) {
            return base.Channel.InsertGarantiaAsync(objGarantiaBE);
        }
        
        public bool UpdateGarantia(MVC_Solicitud.ProxyGarantia.GarantiaBE objGarantiaBE) {
            return base.Channel.UpdateGarantia(objGarantiaBE);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateGarantiaAsync(MVC_Solicitud.ProxyGarantia.GarantiaBE objGarantiaBE) {
            return base.Channel.UpdateGarantiaAsync(objGarantiaBE);
        }
        
        public bool DeleteGarantia(int Id_garantia) {
            return base.Channel.DeleteGarantia(Id_garantia);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteGarantiaAsync(int Id_garantia) {
            return base.Channel.DeleteGarantiaAsync(Id_garantia);
        }
        
        public MVC_Solicitud.ProxyGarantia.GarantiaBE GetGarantiaPorCliente(string Id_cli) {
            return base.Channel.GetGarantiaPorCliente(Id_cli);
        }
        
        public System.Threading.Tasks.Task<MVC_Solicitud.ProxyGarantia.GarantiaBE> GetGarantiaPorClienteAsync(string Id_cli) {
            return base.Channel.GetGarantiaPorClienteAsync(Id_cli);
        }
        
        public MVC_Solicitud.ProxyGarantia.GarantiaBE GetGarantia(int Id_garantia) {
            return base.Channel.GetGarantia(Id_garantia);
        }
        
        public System.Threading.Tasks.Task<MVC_Solicitud.ProxyGarantia.GarantiaBE> GetGarantiaAsync(int Id_garantia) {
            return base.Channel.GetGarantiaAsync(Id_garantia);
        }
        
        public MVC_Solicitud.ProxyGarantia.GarantiaBE[] GetAllGarantias() {
            return base.Channel.GetAllGarantias();
        }
        
        public System.Threading.Tasks.Task<MVC_Solicitud.ProxyGarantia.GarantiaBE[]> GetAllGarantiasAsync() {
            return base.Channel.GetAllGarantiasAsync();
        }
    }
}
