//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudesWEB_GUI.ProxySolicitudes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_SolicitudesCreditos")]
    [System.SerializableAttribute()]
    public partial class SolicitudBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Agen_direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_analistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AprobacionFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoletaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CuotaNroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CuotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Est_desembolsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Est_solicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_aprobacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_desembolsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_pagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_rechazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_solicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_ult_modField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_agenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_analistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float MontCanceladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Monto_soliciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Motivo_rechazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_analistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Num_cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PruebaFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RechazoFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short RetrasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_ult_modField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ld_solicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Agen_direccion {
            get {
                return this.Agen_direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.Agen_direccionField, value) != true)) {
                    this.Agen_direccionField = value;
                    this.RaisePropertyChanged("Agen_direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_analista {
            get {
                return this.Ape_analistaField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_analistaField, value) != true)) {
                    this.Ape_analistaField = value;
                    this.RaisePropertyChanged("Ape_analista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_cli {
            get {
                return this.Ape_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_cliField, value) != true)) {
                    this.Ape_cliField = value;
                    this.RaisePropertyChanged("Ape_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AprobacionFecha {
            get {
                return this.AprobacionFechaField;
            }
            set {
                if ((object.ReferenceEquals(this.AprobacionFechaField, value) != true)) {
                    this.AprobacionFechaField = value;
                    this.RaisePropertyChanged("AprobacionFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boleta {
            get {
                return this.BoletaField;
            }
            set {
                if ((object.ReferenceEquals(this.BoletaField, value) != true)) {
                    this.BoletaField = value;
                    this.RaisePropertyChanged("Boleta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CuotaNro {
            get {
                return this.CuotaNroField;
            }
            set {
                if ((this.CuotaNroField.Equals(value) != true)) {
                    this.CuotaNroField = value;
                    this.RaisePropertyChanged("CuotaNro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Cuotas {
            get {
                return this.CuotasField;
            }
            set {
                if ((this.CuotasField.Equals(value) != true)) {
                    this.CuotasField = value;
                    this.RaisePropertyChanged("Cuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Est_desembolso {
            get {
                return this.Est_desembolsoField;
            }
            set {
                if ((object.ReferenceEquals(this.Est_desembolsoField, value) != true)) {
                    this.Est_desembolsoField = value;
                    this.RaisePropertyChanged("Est_desembolso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Est_solicitud {
            get {
                return this.Est_solicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.Est_solicitudField, value) != true)) {
                    this.Est_solicitudField = value;
                    this.RaisePropertyChanged("Est_solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_aprobacion {
            get {
                return this.Fec_aprobacionField;
            }
            set {
                if ((this.Fec_aprobacionField.Equals(value) != true)) {
                    this.Fec_aprobacionField = value;
                    this.RaisePropertyChanged("Fec_aprobacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_desembolso {
            get {
                return this.Fec_desembolsoField;
            }
            set {
                if ((this.Fec_desembolsoField.Equals(value) != true)) {
                    this.Fec_desembolsoField = value;
                    this.RaisePropertyChanged("Fec_desembolso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_pago {
            get {
                return this.Fec_pagoField;
            }
            set {
                if ((this.Fec_pagoField.Equals(value) != true)) {
                    this.Fec_pagoField = value;
                    this.RaisePropertyChanged("Fec_pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_rechazo {
            get {
                return this.Fec_rechazoField;
            }
            set {
                if ((this.Fec_rechazoField.Equals(value) != true)) {
                    this.Fec_rechazoField = value;
                    this.RaisePropertyChanged("Fec_rechazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg {
            get {
                return this.Fec_regField;
            }
            set {
                if ((this.Fec_regField.Equals(value) != true)) {
                    this.Fec_regField = value;
                    this.RaisePropertyChanged("Fec_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_solicitud {
            get {
                return this.Fec_solicitudField;
            }
            set {
                if ((this.Fec_solicitudField.Equals(value) != true)) {
                    this.Fec_solicitudField = value;
                    this.RaisePropertyChanged("Fec_solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_ult_mod {
            get {
                return this.Fec_ult_modField;
            }
            set {
                if ((this.Fec_ult_modField.Equals(value) != true)) {
                    this.Fec_ult_modField = value;
                    this.RaisePropertyChanged("Fec_ult_mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_agencia {
            get {
                return this.Id_agenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_agenciaField, value) != true)) {
                    this.Id_agenciaField = value;
                    this.RaisePropertyChanged("Id_agencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_analista {
            get {
                return this.Id_analistaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_analistaField, value) != true)) {
                    this.Id_analistaField = value;
                    this.RaisePropertyChanged("Id_analista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_cli {
            get {
                return this.Id_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_cliField, value) != true)) {
                    this.Id_cliField = value;
                    this.RaisePropertyChanged("Id_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float MontCancelado {
            get {
                return this.MontCanceladoField;
            }
            set {
                if ((this.MontCanceladoField.Equals(value) != true)) {
                    this.MontCanceladoField = value;
                    this.RaisePropertyChanged("MontCancelado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto_solici {
            get {
                return this.Monto_soliciField;
            }
            set {
                if ((this.Monto_soliciField.Equals(value) != true)) {
                    this.Monto_soliciField = value;
                    this.RaisePropertyChanged("Monto_solici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivo_rechazo {
            get {
                return this.Motivo_rechazoField;
            }
            set {
                if ((object.ReferenceEquals(this.Motivo_rechazoField, value) != true)) {
                    this.Motivo_rechazoField = value;
                    this.RaisePropertyChanged("Motivo_rechazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_analista {
            get {
                return this.Nom_analistaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_analistaField, value) != true)) {
                    this.Nom_analistaField = value;
                    this.RaisePropertyChanged("Nom_analista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_cli {
            get {
                return this.Nom_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_cliField, value) != true)) {
                    this.Nom_cliField = value;
                    this.RaisePropertyChanged("Nom_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_cuenta {
            get {
                return this.Num_cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.Num_cuentaField, value) != true)) {
                    this.Num_cuentaField = value;
                    this.RaisePropertyChanged("Num_cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUCTO {
            get {
                return this.PRODUCTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCTOField, value) != true)) {
                    this.PRODUCTOField = value;
                    this.RaisePropertyChanged("PRODUCTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PruebaFecha {
            get {
                return this.PruebaFechaField;
            }
            set {
                if ((object.ReferenceEquals(this.PruebaFechaField, value) != true)) {
                    this.PruebaFechaField = value;
                    this.RaisePropertyChanged("PruebaFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RechazoFecha {
            get {
                return this.RechazoFechaField;
            }
            set {
                if ((object.ReferenceEquals(this.RechazoFechaField, value) != true)) {
                    this.RechazoFechaField = value;
                    this.RaisePropertyChanged("RechazoFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Retraso {
            get {
                return this.RetrasoField;
            }
            set {
                if ((this.RetrasoField.Equals(value) != true)) {
                    this.RetrasoField = value;
                    this.RaisePropertyChanged("Retraso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_producto {
            get {
                return this.Tipo_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_productoField, value) != true)) {
                    this.Tipo_productoField = value;
                    this.RaisePropertyChanged("Tipo_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_registro {
            get {
                return this.Usu_registroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_registroField, value) != true)) {
                    this.Usu_registroField = value;
                    this.RaisePropertyChanged("Usu_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_ult_mod {
            get {
                return this.Usu_ult_modField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_ult_modField, value) != true)) {
                    this.Usu_ult_modField = value;
                    this.RaisePropertyChanged("Usu_ult_mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ld_solicitud {
            get {
                return this.ld_solicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.ld_solicitudField, value) != true)) {
                    this.ld_solicitudField = value;
                    this.RaisePropertyChanged("ld_solicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxySolicitudes.IServicioSolicitud")]
    public interface IServicioSolicitud {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetAllSolicitud", ReplyAction="http://tempuri.org/IServicioSolicitud/GetAllSolicitudResponse")]
        SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetAllSolicitud();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetAllSolicitud", ReplyAction="http://tempuri.org/IServicioSolicitud/GetAllSolicitudResponse")]
        System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetAllSolicitudAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetAllSolicitudXAnalista", ReplyAction="http://tempuri.org/IServicioSolicitud/GetAllSolicitudXAnalistaResponse")]
        SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetAllSolicitudXAnalista(string Id_analista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetAllSolicitudXAnalista", ReplyAction="http://tempuri.org/IServicioSolicitud/GetAllSolicitudXAnalistaResponse")]
        System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetAllSolicitudXAnalistaAsync(string Id_analista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetAllSolicitudXCliente", ReplyAction="http://tempuri.org/IServicioSolicitud/GetAllSolicitudXClienteResponse")]
        SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetAllSolicitudXCliente(string Id_cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetAllSolicitudXCliente", ReplyAction="http://tempuri.org/IServicioSolicitud/GetAllSolicitudXClienteResponse")]
        System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetAllSolicitudXClienteAsync(string Id_cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetSolicitudXFechaXAnalista", ReplyAction="http://tempuri.org/IServicioSolicitud/GetSolicitudXFechaXAnalistaResponse")]
        SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetSolicitudXFechaXAnalista(string strCodigo, System.DateTime Fecini, System.DateTime Fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetSolicitudXFechaXAnalista", ReplyAction="http://tempuri.org/IServicioSolicitud/GetSolicitudXFechaXAnalistaResponse")]
        System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetSolicitudXFechaXAnalistaAsync(string strCodigo, System.DateTime Fecini, System.DateTime Fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetSolicitudXEstado", ReplyAction="http://tempuri.org/IServicioSolicitud/GetSolicitudXEstadoResponse")]
        SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetSolicitudXEstado(short Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetSolicitudXEstado", ReplyAction="http://tempuri.org/IServicioSolicitud/GetSolicitudXEstadoResponse")]
        System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetSolicitudXEstadoAsync(short Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetSolicitudXEstadoxAnalista", ReplyAction="http://tempuri.org/IServicioSolicitud/GetSolicitudXEstadoxAnalistaResponse")]
        SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetSolicitudXEstadoxAnalista(short Estado, string codAnalista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetSolicitudXEstadoxAnalista", ReplyAction="http://tempuri.org/IServicioSolicitud/GetSolicitudXEstadoxAnalistaResponse")]
        System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetSolicitudXEstadoxAnalistaAsync(short Estado, string codAnalista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetPagoxSolicitud", ReplyAction="http://tempuri.org/IServicioSolicitud/GetPagoxSolicitudResponse")]
        SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetPagoxSolicitud(string Id_solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetPagoxSolicitud", ReplyAction="http://tempuri.org/IServicioSolicitud/GetPagoxSolicitudResponse")]
        System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetPagoxSolicitudAsync(string Id_solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetSolicitudXFechaXEstado", ReplyAction="http://tempuri.org/IServicioSolicitud/GetSolicitudXFechaXEstadoResponse")]
        SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetSolicitudXFechaXEstado(short Estado, System.DateTime Fecini, System.DateTime Fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitud/GetSolicitudXFechaXEstado", ReplyAction="http://tempuri.org/IServicioSolicitud/GetSolicitudXFechaXEstadoResponse")]
        System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetSolicitudXFechaXEstadoAsync(short Estado, System.DateTime Fecini, System.DateTime Fecfin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSolicitudChannel : SolicitudesWEB_GUI.ProxySolicitudes.IServicioSolicitud, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSolicitudClient : System.ServiceModel.ClientBase<SolicitudesWEB_GUI.ProxySolicitudes.IServicioSolicitud>, SolicitudesWEB_GUI.ProxySolicitudes.IServicioSolicitud {
        
        public ServicioSolicitudClient() {
        }
        
        public ServicioSolicitudClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSolicitudClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSolicitudClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSolicitudClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetAllSolicitud() {
            return base.Channel.GetAllSolicitud();
        }
        
        public System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetAllSolicitudAsync() {
            return base.Channel.GetAllSolicitudAsync();
        }
        
        public SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetAllSolicitudXAnalista(string Id_analista) {
            return base.Channel.GetAllSolicitudXAnalista(Id_analista);
        }
        
        public System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetAllSolicitudXAnalistaAsync(string Id_analista) {
            return base.Channel.GetAllSolicitudXAnalistaAsync(Id_analista);
        }
        
        public SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetAllSolicitudXCliente(string Id_cli) {
            return base.Channel.GetAllSolicitudXCliente(Id_cli);
        }
        
        public System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetAllSolicitudXClienteAsync(string Id_cli) {
            return base.Channel.GetAllSolicitudXClienteAsync(Id_cli);
        }
        
        public SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetSolicitudXFechaXAnalista(string strCodigo, System.DateTime Fecini, System.DateTime Fecfin) {
            return base.Channel.GetSolicitudXFechaXAnalista(strCodigo, Fecini, Fecfin);
        }
        
        public System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetSolicitudXFechaXAnalistaAsync(string strCodigo, System.DateTime Fecini, System.DateTime Fecfin) {
            return base.Channel.GetSolicitudXFechaXAnalistaAsync(strCodigo, Fecini, Fecfin);
        }
        
        public SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetSolicitudXEstado(short Estado) {
            return base.Channel.GetSolicitudXEstado(Estado);
        }
        
        public System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetSolicitudXEstadoAsync(short Estado) {
            return base.Channel.GetSolicitudXEstadoAsync(Estado);
        }
        
        public SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetSolicitudXEstadoxAnalista(short Estado, string codAnalista) {
            return base.Channel.GetSolicitudXEstadoxAnalista(Estado, codAnalista);
        }
        
        public System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetSolicitudXEstadoxAnalistaAsync(short Estado, string codAnalista) {
            return base.Channel.GetSolicitudXEstadoxAnalistaAsync(Estado, codAnalista);
        }
        
        public SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetPagoxSolicitud(string Id_solicitud) {
            return base.Channel.GetPagoxSolicitud(Id_solicitud);
        }
        
        public System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetPagoxSolicitudAsync(string Id_solicitud) {
            return base.Channel.GetPagoxSolicitudAsync(Id_solicitud);
        }
        
        public SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[] GetSolicitudXFechaXEstado(short Estado, System.DateTime Fecini, System.DateTime Fecfin) {
            return base.Channel.GetSolicitudXFechaXEstado(Estado, Fecini, Fecfin);
        }
        
        public System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxySolicitudes.SolicitudBE[]> GetSolicitudXFechaXEstadoAsync(short Estado, System.DateTime Fecini, System.DateTime Fecfin) {
            return base.Channel.GetSolicitudXFechaXEstadoAsync(Estado, Fecini, Fecfin);
        }
    }
}
