//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CreditosEntities : DbContext
    {
        public CreditosEntities()
            : base("name=CreditosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Agencia> Tb_Agencia { get; set; }
        public virtual DbSet<Tb_Analista> Tb_Analista { get; set; }
        public virtual DbSet<Tb_Cliente> Tb_Cliente { get; set; }
        public virtual DbSet<Tb_Credito_Hipotecario> Tb_Credito_Hipotecario { get; set; }
        public virtual DbSet<Tb_Credito_vehicular> Tb_Credito_vehicular { get; set; }
        public virtual DbSet<Tb_Fuente_Ingreso> Tb_Fuente_Ingreso { get; set; }
        public virtual DbSet<Tb_Garantia> Tb_Garantia { get; set; }
        public virtual DbSet<Tb_Pagos> Tb_Pagos { get; set; }
        public virtual DbSet<Tb_Prestamo_Facil> Tb_Prestamo_Facil { get; set; }
        public virtual DbSet<Tb_Solicitud> Tb_Solicitud { get; set; }
        public virtual DbSet<Tb_Tarjeta_Credito> Tb_Tarjeta_Credito { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<tb_Usuario> tb_Usuario { get; set; }
        public virtual DbSet<vw_Detalle_Agencia> vw_Detalle_Agencia { get; set; }
        public virtual DbSet<vw_Detalle_Cliente> vw_Detalle_Cliente { get; set; }
        public virtual DbSet<vw_Detalle_Garantia> vw_Detalle_Garantia { get; set; }
        public virtual DbSet<vw_Detalle_Solicitud> vw_Detalle_Solicitud { get; set; }
        public virtual DbSet<vw_Ingresos_Clientes> vw_Ingresos_Clientes { get; set; }
        public virtual DbSet<vw_PagosDetalles> vw_PagosDetalles { get; set; }
        public virtual DbSet<vw_SolicitudesXAgencia> vw_SolicitudesXAgencia { get; set; }
        public virtual DbSet<vw_VistaAnalista> vw_VistaAnalista { get; set; }
    
        public virtual int usp_ActualizarCliente(string vcod, string vnomb, string vApelli, string vdniCli, string vruc, string vsexo, Nullable<System.DateTime> vfecNac, string vEduc, Nullable<int> vEst_Civil, string vEmail, string vIdubi, Nullable<int> vEst_Cli, string vUsu_Ult_Mod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var vnombParameter = vnomb != null ?
                new ObjectParameter("vnomb", vnomb) :
                new ObjectParameter("vnomb", typeof(string));
    
            var vApelliParameter = vApelli != null ?
                new ObjectParameter("vApelli", vApelli) :
                new ObjectParameter("vApelli", typeof(string));
    
            var vdniCliParameter = vdniCli != null ?
                new ObjectParameter("vdniCli", vdniCli) :
                new ObjectParameter("vdniCli", typeof(string));
    
            var vrucParameter = vruc != null ?
                new ObjectParameter("vruc", vruc) :
                new ObjectParameter("vruc", typeof(string));
    
            var vsexoParameter = vsexo != null ?
                new ObjectParameter("vsexo", vsexo) :
                new ObjectParameter("vsexo", typeof(string));
    
            var vfecNacParameter = vfecNac.HasValue ?
                new ObjectParameter("vfecNac", vfecNac) :
                new ObjectParameter("vfecNac", typeof(System.DateTime));
    
            var vEducParameter = vEduc != null ?
                new ObjectParameter("vEduc", vEduc) :
                new ObjectParameter("vEduc", typeof(string));
    
            var vEst_CivilParameter = vEst_Civil.HasValue ?
                new ObjectParameter("vEst_Civil", vEst_Civil) :
                new ObjectParameter("vEst_Civil", typeof(int));
    
            var vEmailParameter = vEmail != null ?
                new ObjectParameter("vEmail", vEmail) :
                new ObjectParameter("vEmail", typeof(string));
    
            var vIdubiParameter = vIdubi != null ?
                new ObjectParameter("vIdubi", vIdubi) :
                new ObjectParameter("vIdubi", typeof(string));
    
            var vEst_CliParameter = vEst_Cli.HasValue ?
                new ObjectParameter("vEst_Cli", vEst_Cli) :
                new ObjectParameter("vEst_Cli", typeof(int));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCliente", vcodParameter, vnombParameter, vApelliParameter, vdniCliParameter, vrucParameter, vsexoParameter, vfecNacParameter, vEducParameter, vEst_CivilParameter, vEmailParameter, vIdubiParameter, vEst_CliParameter, vUsu_Ult_ModParameter);
        }
    
        public virtual int usp_ActualizarGarantia(Nullable<int> id_garantia, string tip_garantia, string des_garantia, Nullable<decimal> valor_garantia, string id_cli, Nullable<int> est_garania, string usu_ult_mod)
        {
            var id_garantiaParameter = id_garantia.HasValue ?
                new ObjectParameter("id_garantia", id_garantia) :
                new ObjectParameter("id_garantia", typeof(int));
    
            var tip_garantiaParameter = tip_garantia != null ?
                new ObjectParameter("tip_garantia", tip_garantia) :
                new ObjectParameter("tip_garantia", typeof(string));
    
            var des_garantiaParameter = des_garantia != null ?
                new ObjectParameter("des_garantia", des_garantia) :
                new ObjectParameter("des_garantia", typeof(string));
    
            var valor_garantiaParameter = valor_garantia.HasValue ?
                new ObjectParameter("valor_garantia", valor_garantia) :
                new ObjectParameter("valor_garantia", typeof(decimal));
    
            var id_cliParameter = id_cli != null ?
                new ObjectParameter("id_cli", id_cli) :
                new ObjectParameter("id_cli", typeof(string));
    
            var est_garaniaParameter = est_garania.HasValue ?
                new ObjectParameter("est_garania", est_garania) :
                new ObjectParameter("est_garania", typeof(int));
    
            var usu_ult_modParameter = usu_ult_mod != null ?
                new ObjectParameter("usu_ult_mod", usu_ult_mod) :
                new ObjectParameter("usu_ult_mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarGarantia", id_garantiaParameter, tip_garantiaParameter, des_garantiaParameter, valor_garantiaParameter, id_cliParameter, est_garaniaParameter, usu_ult_modParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarCliente_Result> usp_ConsultarCliente(string vcos)
        {
            var vcosParameter = vcos != null ?
                new ObjectParameter("vcos", vcos) :
                new ObjectParameter("vcos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarCliente_Result>("usp_ConsultarCliente", vcosParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarGarantia_Result> usp_ConsultarGarantia(Nullable<int> id_garantia)
        {
            var id_garantiaParameter = id_garantia.HasValue ?
                new ObjectParameter("id_garantia", id_garantia) :
                new ObjectParameter("id_garantia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarGarantia_Result>("usp_ConsultarGarantia", id_garantiaParameter);
        }
    
        public virtual int usp_EliminarCliente(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCliente", vcodParameter);
        }
    
        public virtual int usp_EliminarGarantia(Nullable<int> id_garantia)
        {
            var id_garantiaParameter = id_garantia.HasValue ?
                new ObjectParameter("id_garantia", id_garantia) :
                new ObjectParameter("id_garantia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarGarantia", id_garantiaParameter);
        }
    
        public virtual int usp_InsertarCliente(string vnomb, string vApelli, string vdniCli, string vruc, string vsexo, Nullable<System.DateTime> vfecNac, string vEduc, Nullable<int> vEst_Civil, string vEmail, string vIdubi, Nullable<int> vEst_Cli, string vUsu_Registro)
        {
            var vnombParameter = vnomb != null ?
                new ObjectParameter("vnomb", vnomb) :
                new ObjectParameter("vnomb", typeof(string));
    
            var vApelliParameter = vApelli != null ?
                new ObjectParameter("vApelli", vApelli) :
                new ObjectParameter("vApelli", typeof(string));
    
            var vdniCliParameter = vdniCli != null ?
                new ObjectParameter("vdniCli", vdniCli) :
                new ObjectParameter("vdniCli", typeof(string));
    
            var vrucParameter = vruc != null ?
                new ObjectParameter("vruc", vruc) :
                new ObjectParameter("vruc", typeof(string));
    
            var vsexoParameter = vsexo != null ?
                new ObjectParameter("vsexo", vsexo) :
                new ObjectParameter("vsexo", typeof(string));
    
            var vfecNacParameter = vfecNac.HasValue ?
                new ObjectParameter("vfecNac", vfecNac) :
                new ObjectParameter("vfecNac", typeof(System.DateTime));
    
            var vEducParameter = vEduc != null ?
                new ObjectParameter("vEduc", vEduc) :
                new ObjectParameter("vEduc", typeof(string));
    
            var vEst_CivilParameter = vEst_Civil.HasValue ?
                new ObjectParameter("vEst_Civil", vEst_Civil) :
                new ObjectParameter("vEst_Civil", typeof(int));
    
            var vEmailParameter = vEmail != null ?
                new ObjectParameter("vEmail", vEmail) :
                new ObjectParameter("vEmail", typeof(string));
    
            var vIdubiParameter = vIdubi != null ?
                new ObjectParameter("vIdubi", vIdubi) :
                new ObjectParameter("vIdubi", typeof(string));
    
            var vEst_CliParameter = vEst_Cli.HasValue ?
                new ObjectParameter("vEst_Cli", vEst_Cli) :
                new ObjectParameter("vEst_Cli", typeof(int));
    
            var vUsu_RegistroParameter = vUsu_Registro != null ?
                new ObjectParameter("vUsu_Registro", vUsu_Registro) :
                new ObjectParameter("vUsu_Registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCliente", vnombParameter, vApelliParameter, vdniCliParameter, vrucParameter, vsexoParameter, vfecNacParameter, vEducParameter, vEst_CivilParameter, vEmailParameter, vIdubiParameter, vEst_CliParameter, vUsu_RegistroParameter);
        }
    
        public virtual int usp_InsertarGarantia(string tip_garantia, string des_garantia, Nullable<decimal> valor_garantia, string id_cli, Nullable<int> est_garantia, string usu_registro)
        {
            var tip_garantiaParameter = tip_garantia != null ?
                new ObjectParameter("Tip_garantia", tip_garantia) :
                new ObjectParameter("Tip_garantia", typeof(string));
    
            var des_garantiaParameter = des_garantia != null ?
                new ObjectParameter("Des_garantia", des_garantia) :
                new ObjectParameter("Des_garantia", typeof(string));
    
            var valor_garantiaParameter = valor_garantia.HasValue ?
                new ObjectParameter("Valor_garantia", valor_garantia) :
                new ObjectParameter("Valor_garantia", typeof(decimal));
    
            var id_cliParameter = id_cli != null ?
                new ObjectParameter("Id_cli", id_cli) :
                new ObjectParameter("Id_cli", typeof(string));
    
            var est_garantiaParameter = est_garantia.HasValue ?
                new ObjectParameter("Est_garantia", est_garantia) :
                new ObjectParameter("Est_garantia", typeof(int));
    
            var usu_registroParameter = usu_registro != null ?
                new ObjectParameter("Usu_registro", usu_registro) :
                new ObjectParameter("Usu_registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarGarantia", tip_garantiaParameter, des_garantiaParameter, valor_garantiaParameter, id_cliParameter, est_garantiaParameter, usu_registroParameter);
        }
    
        public virtual ObjectResult<usp_ListarCliente_Result> usp_ListarCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarCliente_Result>("usp_ListarCliente");
        }
    
        public virtual ObjectResult<usp_ListarGarantia_Result> usp_ListarGarantia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarGarantia_Result>("usp_ListarGarantia");
        }
    
        public virtual ObjectResult<usp_ListarGarantiaXcliente_Result> usp_ListarGarantiaXcliente(string vId_cliente)
        {
            var vId_clienteParameter = vId_cliente != null ?
                new ObjectParameter("vId_cliente", vId_cliente) :
                new ObjectParameter("vId_cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarGarantiaXcliente_Result>("usp_ListarGarantiaXcliente", vId_clienteParameter);
        }
    
        public virtual ObjectResult<usp_ListarSolicitudXAna_Result> usp_ListarSolicitudXAna(string vId_analista)
        {
            var vId_analistaParameter = vId_analista != null ?
                new ObjectParameter("vId_analista", vId_analista) :
                new ObjectParameter("vId_analista", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarSolicitudXAna_Result>("usp_ListarSolicitudXAna", vId_analistaParameter);
        }
    
        public virtual ObjectResult<usp_ListarSolicitudXcliente_Result> usp_ListarSolicitudXcliente(string vId_cliente)
        {
            var vId_clienteParameter = vId_cliente != null ?
                new ObjectParameter("vId_cliente", vId_cliente) :
                new ObjectParameter("vId_cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarSolicitudXcliente_Result>("usp_ListarSolicitudXcliente", vId_clienteParameter);
        }
    
        public virtual ObjectResult<usp_RankingAnalistas_Result> usp_RankingAnalistas(Nullable<int> vTop, Nullable<int> vEst_soli)
        {
            var vTopParameter = vTop.HasValue ?
                new ObjectParameter("vTop", vTop) :
                new ObjectParameter("vTop", typeof(int));
    
            var vEst_soliParameter = vEst_soli.HasValue ?
                new ObjectParameter("vEst_soli", vEst_soli) :
                new ObjectParameter("vEst_soli", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RankingAnalistas_Result>("usp_RankingAnalistas", vTopParameter, vEst_soliParameter);
        }
    
        public virtual ObjectResult<usp_ListarSolicitudEstado_Result> usp_ListarSolicitudEstado(Nullable<int> vEstado)
        {
            var vEstadoParameter = vEstado.HasValue ?
                new ObjectParameter("vEstado", vEstado) :
                new ObjectParameter("vEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarSolicitudEstado_Result>("usp_ListarSolicitudEstado", vEstadoParameter);
        }
    
        public virtual ObjectResult<usp_Ubigeo_Departamentos_Result> usp_Ubigeo_Departamentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_Departamentos_Result>("usp_Ubigeo_Departamentos");
        }
    
        public virtual ObjectResult<usp_Ubigeo_DistritosProvinciaDepartamento_Result> usp_Ubigeo_DistritosProvinciaDepartamento(string idDepartamento, string idProvincia)
        {
            var idDepartamentoParameter = idDepartamento != null ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(string));
    
            var idProvinciaParameter = idProvincia != null ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_DistritosProvinciaDepartamento_Result>("usp_Ubigeo_DistritosProvinciaDepartamento", idDepartamentoParameter, idProvinciaParameter);
        }
    
        public virtual ObjectResult<usp_Ubigeo_ProvinciasDepartamento_Result> usp_Ubigeo_ProvinciasDepartamento(string idDepartamento)
        {
            var idDepartamentoParameter = idDepartamento != null ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_ProvinciasDepartamento_Result>("usp_Ubigeo_ProvinciasDepartamento", idDepartamentoParameter);
        }
    
        public virtual ObjectResult<usp_ListarPagoSolicitud_Result> usp_ListarPagoSolicitud(string vId_solicitud)
        {
            var vId_solicitudParameter = vId_solicitud != null ?
                new ObjectParameter("vId_solicitud", vId_solicitud) :
                new ObjectParameter("vId_solicitud", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarPagoSolicitud_Result>("usp_ListarPagoSolicitud", vId_solicitudParameter);
        }
    }
}
