//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Analista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Analista()
        {
            this.Tb_Solicitud = new HashSet<Tb_Solicitud>();
        }
    
        public string Id_analista { get; set; }
        public string Nom_analista { get; set; }
        public string Ape_analista { get; set; }
        public string Id_agencia { get; set; }
        public System.DateTime Fec_ingreso { get; set; }
        public string DNI_analista { get; set; }
        public string Email_analista { get; set; }
    
        public virtual Tb_Agencia Tb_Agencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Solicitud> Tb_Solicitud { get; set; }
    }
}
