//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Credito_Hipotecario
    {
        public string Id_Det_Credito_Hipotecario { get; set; }
        public string Id_solicitud { get; set; }
        public string Tipo_hipotecario { get; set; }
        public Nullable<decimal> Valor_inmueble { get; set; }
        public Nullable<decimal> Cuota_inicial { get; set; }
        public Nullable<int> Plazo { get; set; }
        public string Destino_Compra { get; set; }
        public Nullable<int> Est_credito_hipotecario { get; set; }
        public System.DateTime Fec_reg { get; set; }
        public string Usu_registro { get; set; }
        public Nullable<System.DateTime> Fec_ult_mod { get; set; }
        public string Usu_ult_mod { get; set; }
    
        public virtual Tb_Solicitud Tb_Solicitud { get; set; }
    }
}
