//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Cliente()
        {
            this.Tb_Fuente_Ingreso = new HashSet<Tb_Fuente_Ingreso>();
            this.Tb_Garantia = new HashSet<Tb_Garantia>();
            this.Tb_Solicitud = new HashSet<Tb_Solicitud>();
        }
    
        public string Id_cli { get; set; }
        public string Nom_cli { get; set; }
        public string Ape_cli { get; set; }
        public string Dni_cli { get; set; }
        public string Ruc_cli { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Fec_nacimiento { get; set; }
        public string Nivel_educacion { get; set; }
        public Nullable<int> Estado_civil { get; set; }
        public string Email { get; set; }
        public string Id_ubigeo { get; set; }
        public Nullable<int> Est_cli { get; set; }
        public System.DateTime Fec_reg { get; set; }
        public string Usu_registro { get; set; }
        public Nullable<System.DateTime> Fec_ult_mod { get; set; }
        public string Usu_ult_mod { get; set; }
    
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Fuente_Ingreso> Tb_Fuente_Ingreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Garantia> Tb_Garantia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Solicitud> Tb_Solicitud { get; set; }
    }
}
