//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Fuente_Ingreso
    {
        public int Id_ingreso { get; set; }
        public string Id_cli { get; set; }
        public Nullable<int> Tipo_ingreso { get; set; }
        public Nullable<decimal> Monto_ingreso { get; set; }
        public System.DateTime Fec_inicio { get; set; }
    
        public virtual Tb_Cliente Tb_Cliente { get; set; }
    }
}
