//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Garantia
    {
        public int Id_garantia { get; set; }
        public string Tip_garantia { get; set; }
        public string Des_garantia { get; set; }
        public Nullable<decimal> Valor_garantia { get; set; }
        public string Id_cli { get; set; }
        public Nullable<int> Est_garantia { get; set; }
        public System.DateTime Fec_reg { get; set; }
        public string Usu_registro { get; set; }
        public Nullable<System.DateTime> Fec_ult_mod { get; set; }
        public string Usu_ult_mod { get; set; }
    
        public virtual Tb_Cliente Tb_Cliente { get; set; }
    }
}
