//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Prestamo_Facil
    {
        public string Id_Det_Prestamo_Facil { get; set; }
        public string Id_solicitud { get; set; }
        public string Tipo_prestamo { get; set; }
        public string Tipo_desembolso { get; set; }
        public Nullable<int> Plazo { get; set; }
    
        public virtual Tb_Solicitud Tb_Solicitud { get; set; }
    }
}
