//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Solicitud()
        {
            this.Tb_Credito_Hipotecario = new HashSet<Tb_Credito_Hipotecario>();
            this.Tb_Credito_vehicular = new HashSet<Tb_Credito_vehicular>();
            this.Tb_Pagos = new HashSet<Tb_Pagos>();
            this.Tb_Prestamo_Facil = new HashSet<Tb_Prestamo_Facil>();
            this.Tb_Tarjeta_Credito = new HashSet<Tb_Tarjeta_Credito>();
        }
    
        public string Id_solicitud { get; set; }
        public string Id_cli { get; set; }
        public string Id_analista { get; set; }
        public Nullable<int> Tipo_producto { get; set; }
        public System.DateTime Fec_solicitud { get; set; }
        public Nullable<decimal> Monto_solici { get; set; }
        public string Num_cuenta { get; set; }
        public Nullable<int> Est_solicitud { get; set; }
        public Nullable<System.DateTime> Fec_aprobacion { get; set; }
        public Nullable<System.DateTime> Fec_rechazo { get; set; }
        public string Motivo_rechazo { get; set; }
        public Nullable<int> Est_desembolso { get; set; }
        public Nullable<System.DateTime> Fec_desembolso { get; set; }
        public Nullable<System.DateTime> Fec_pago { get; set; }
        public System.DateTime Fec_reg { get; set; }
        public string Usu_registro { get; set; }
        public Nullable<System.DateTime> Fec_ult_mod { get; set; }
        public string Usu_ult_mod { get; set; }
        public Nullable<int> Cuotas { get; set; }
    
        public virtual Tb_Analista Tb_Analista { get; set; }
        public virtual Tb_Cliente Tb_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Credito_Hipotecario> Tb_Credito_Hipotecario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Credito_vehicular> Tb_Credito_vehicular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Pagos> Tb_Pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Prestamo_Facil> Tb_Prestamo_Facil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Tarjeta_Credito> Tb_Tarjeta_Credito { get; set; }
    }
}
