//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Tarjeta_Credito
    {
        public string Id_Det_Tarjeta_Credito { get; set; }
        public string Id_solicitud { get; set; }
        public string Marca { get; set; }
        public string Tipo { get; set; }
        public string Moneda { get; set; }
        public string Dispone_efectivo { get; set; }
    
        public virtual Tb_Solicitud Tb_Solicitud { get; set; }
    }
}
