//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Detalle_Cliente
    {
        public string Id_cli { get; set; }
        public string Nom_cli { get; set; }
        public string Ape_cli { get; set; }
        public string Dni_cli { get; set; }
        public string Ruc_cli { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Fec_nacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Nivel_educacion { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> Estado_civil { get; set; }
        public string Email { get; set; }
        public string Id_ubigeo { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
        public string Estado_cliente { get; set; }
        public Nullable<int> Est_cli { get; set; }
    }
}
