//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Ingresos_Clientes
    {
        public string ID_del_Cliente { get; set; }
        public string Nombre_del_cliente { get; set; }
        public Nullable<int> Tipo_de_ingresos { get; set; }
        public string Ingreso_descripción { get; set; }
        public Nullable<decimal> Ingresos { get; set; }
        public System.DateTime Inicio_percepción_de_ingreso { get; set; }
    }
}
