//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PagosDetalles
    {
        public string Boleta { get; set; }
        public string Id_solicitud { get; set; }
        public string Nombre_Completo { get; set; }
        public string Id_cli { get; set; }
        public Nullable<decimal> Monto_cancelado { get; set; }
        public Nullable<int> Cuota_numero { get; set; }
        public Nullable<int> Cuotas { get; set; }
        public Nullable<System.DateTime> Fec_pago { get; set; }
        public Nullable<System.DateTime> Fec_cancelacion { get; set; }
        public Nullable<int> RetrasoPago { get; set; }
    }
}
