//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SolicitudesCreditos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaAnalista
    {
        public string Id_analista { get; set; }
        public string Nom_analista { get; set; }
        public string Ape_analista { get; set; }
        public string Id_agencia { get; set; }
        public string Nom_agencia { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
        public string Agen_direccion { get; set; }
        public System.DateTime Fec_ingreso { get; set; }
        public string DNI_analista { get; set; }
        public string Email_analista { get; set; }
    }
}
