//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudesAppWindows.ProxyUbigeo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UbigeoBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_SolicitudesCreditos")]
    [System.SerializableAttribute()]
    public partial class UbigeoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistriroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProvinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distriro {
            get {
                return this.DistriroField;
            }
            set {
                if ((object.ReferenceEquals(this.DistriroField, value) != true)) {
                    this.DistriroField = value;
                    this.RaisePropertyChanged("Distriro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idDepartamento {
            get {
                return this.idDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.idDepartamentoField, value) != true)) {
                    this.idDepartamentoField = value;
                    this.RaisePropertyChanged("idDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idDistrito {
            get {
                return this.idDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.idDistritoField, value) != true)) {
                    this.idDistritoField = value;
                    this.RaisePropertyChanged("idDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.idProvinciaField, value) != true)) {
                    this.idProvinciaField = value;
                    this.RaisePropertyChanged("idProvincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUbigeo.IServicioUbigeo")]
    public interface IServicioUbigeo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetDepartamentos", ReplyAction="http://tempuri.org/IServicioUbigeo/GetDepartamentosResponse")]
        SolicitudesAppWindows.ProxyUbigeo.UbigeoBE[] GetDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetDepartamentos", ReplyAction="http://tempuri.org/IServicioUbigeo/GetDepartamentosResponse")]
        System.Threading.Tasks.Task<SolicitudesAppWindows.ProxyUbigeo.UbigeoBE[]> GetDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetProvincias", ReplyAction="http://tempuri.org/IServicioUbigeo/GetProvinciasResponse")]
        SolicitudesAppWindows.ProxyUbigeo.UbigeoBE[] GetProvincias(string idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetProvincias", ReplyAction="http://tempuri.org/IServicioUbigeo/GetProvinciasResponse")]
        System.Threading.Tasks.Task<SolicitudesAppWindows.ProxyUbigeo.UbigeoBE[]> GetProvinciasAsync(string idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetDistritos", ReplyAction="http://tempuri.org/IServicioUbigeo/GetDistritosResponse")]
        SolicitudesAppWindows.ProxyUbigeo.UbigeoBE[] GetDistritos(string idDepartamento, string idProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetDistritos", ReplyAction="http://tempuri.org/IServicioUbigeo/GetDistritosResponse")]
        System.Threading.Tasks.Task<SolicitudesAppWindows.ProxyUbigeo.UbigeoBE[]> GetDistritosAsync(string idDepartamento, string idProvincia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUbigeoChannel : SolicitudesAppWindows.ProxyUbigeo.IServicioUbigeo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUbigeoClient : System.ServiceModel.ClientBase<SolicitudesAppWindows.ProxyUbigeo.IServicioUbigeo>, SolicitudesAppWindows.ProxyUbigeo.IServicioUbigeo {
        
        public ServicioUbigeoClient() {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbigeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolicitudesAppWindows.ProxyUbigeo.UbigeoBE[] GetDepartamentos() {
            return base.Channel.GetDepartamentos();
        }
        
        public System.Threading.Tasks.Task<SolicitudesAppWindows.ProxyUbigeo.UbigeoBE[]> GetDepartamentosAsync() {
            return base.Channel.GetDepartamentosAsync();
        }
        
        public SolicitudesAppWindows.ProxyUbigeo.UbigeoBE[] GetProvincias(string idDepartamento) {
            return base.Channel.GetProvincias(idDepartamento);
        }
        
        public System.Threading.Tasks.Task<SolicitudesAppWindows.ProxyUbigeo.UbigeoBE[]> GetProvinciasAsync(string idDepartamento) {
            return base.Channel.GetProvinciasAsync(idDepartamento);
        }
        
        public SolicitudesAppWindows.ProxyUbigeo.UbigeoBE[] GetDistritos(string idDepartamento, string idProvincia) {
            return base.Channel.GetDistritos(idDepartamento, idProvincia);
        }
        
        public System.Threading.Tasks.Task<SolicitudesAppWindows.ProxyUbigeo.UbigeoBE[]> GetDistritosAsync(string idDepartamento, string idProvincia) {
            return base.Channel.GetDistritosAsync(idDepartamento, idProvincia);
        }
    }
}
