//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudesWEB_GUI.ProxyAnalistas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnalistaBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_SolicitudesCreditos")]
    [System.SerializableAttribute()]
    public partial class AnalistaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_analistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNI_analistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_analistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_IngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_agenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_analistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Net_valueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_analistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroSolicitudesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_analista {
            get {
                return this.Ape_analistaField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_analistaField, value) != true)) {
                    this.Ape_analistaField = value;
                    this.RaisePropertyChanged("Ape_analista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellNombre {
            get {
                return this.ApellNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellNombreField, value) != true)) {
                    this.ApellNombreField = value;
                    this.RaisePropertyChanged("ApellNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI_analista {
            get {
                return this.DNI_analistaField;
            }
            set {
                if ((object.ReferenceEquals(this.DNI_analistaField, value) != true)) {
                    this.DNI_analistaField = value;
                    this.RaisePropertyChanged("DNI_analista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_analista {
            get {
                return this.Email_analistaField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_analistaField, value) != true)) {
                    this.Email_analistaField = value;
                    this.RaisePropertyChanged("Email_analista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ingreso {
            get {
                return this.Fec_IngresoField;
            }
            set {
                if ((this.Fec_IngresoField.Equals(value) != true)) {
                    this.Fec_IngresoField = value;
                    this.RaisePropertyChanged("Fec_Ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_agencia {
            get {
                return this.Id_agenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_agenciaField, value) != true)) {
                    this.Id_agenciaField = value;
                    this.RaisePropertyChanged("Id_agencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_analista {
            get {
                return this.Id_analistaField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_analistaField, value) != true)) {
                    this.Id_analistaField = value;
                    this.RaisePropertyChanged("Id_analista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Net_value {
            get {
                return this.Net_valueField;
            }
            set {
                if ((this.Net_valueField.Equals(value) != true)) {
                    this.Net_valueField = value;
                    this.RaisePropertyChanged("Net_value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_analista {
            get {
                return this.Nom_analistaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_analistaField, value) != true)) {
                    this.Nom_analistaField = value;
                    this.RaisePropertyChanged("Nom_analista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroSolicitudes {
            get {
                return this.NumeroSolicitudesField;
            }
            set {
                if ((this.NumeroSolicitudesField.Equals(value) != true)) {
                    this.NumeroSolicitudesField = value;
                    this.RaisePropertyChanged("NumeroSolicitudes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyAnalistas.IservicioAnalista")]
    public interface IservicioAnalista {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IservicioAnalista/GetRankingAnalista", ReplyAction="http://tempuri.org/IservicioAnalista/GetRankingAnalistaResponse")]
        SolicitudesWEB_GUI.ProxyAnalistas.AnalistaBE[] GetRankingAnalista(int vTop, int vEstSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IservicioAnalista/GetRankingAnalista", ReplyAction="http://tempuri.org/IservicioAnalista/GetRankingAnalistaResponse")]
        System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxyAnalistas.AnalistaBE[]> GetRankingAnalistaAsync(int vTop, int vEstSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IservicioAnalista/GetAllAnalista", ReplyAction="http://tempuri.org/IservicioAnalista/GetAllAnalistaResponse")]
        SolicitudesWEB_GUI.ProxyAnalistas.AnalistaBE[] GetAllAnalista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IservicioAnalista/GetAllAnalista", ReplyAction="http://tempuri.org/IservicioAnalista/GetAllAnalistaResponse")]
        System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxyAnalistas.AnalistaBE[]> GetAllAnalistaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IservicioAnalista/GetContarAnalistasXSolicitudes", ReplyAction="http://tempuri.org/IservicioAnalista/GetContarAnalistasXSolicitudesResponse")]
        short GetContarAnalistasXSolicitudes(string strCod, short Est_Solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IservicioAnalista/GetContarAnalistasXSolicitudes", ReplyAction="http://tempuri.org/IservicioAnalista/GetContarAnalistasXSolicitudesResponse")]
        System.Threading.Tasks.Task<short> GetContarAnalistasXSolicitudesAsync(string strCod, short Est_Solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IservicioAnalista/GetAnalista", ReplyAction="http://tempuri.org/IservicioAnalista/GetAnalistaResponse")]
        SolicitudesWEB_GUI.ProxyAnalistas.AnalistaBE GetAnalista(string Id_analista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IservicioAnalista/GetAnalista", ReplyAction="http://tempuri.org/IservicioAnalista/GetAnalistaResponse")]
        System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxyAnalistas.AnalistaBE> GetAnalistaAsync(string Id_analista);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IservicioAnalistaChannel : SolicitudesWEB_GUI.ProxyAnalistas.IservicioAnalista, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IservicioAnalistaClient : System.ServiceModel.ClientBase<SolicitudesWEB_GUI.ProxyAnalistas.IservicioAnalista>, SolicitudesWEB_GUI.ProxyAnalistas.IservicioAnalista {
        
        public IservicioAnalistaClient() {
        }
        
        public IservicioAnalistaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IservicioAnalistaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IservicioAnalistaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IservicioAnalistaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolicitudesWEB_GUI.ProxyAnalistas.AnalistaBE[] GetRankingAnalista(int vTop, int vEstSolicitud) {
            return base.Channel.GetRankingAnalista(vTop, vEstSolicitud);
        }
        
        public System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxyAnalistas.AnalistaBE[]> GetRankingAnalistaAsync(int vTop, int vEstSolicitud) {
            return base.Channel.GetRankingAnalistaAsync(vTop, vEstSolicitud);
        }
        
        public SolicitudesWEB_GUI.ProxyAnalistas.AnalistaBE[] GetAllAnalista() {
            return base.Channel.GetAllAnalista();
        }
        
        public System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxyAnalistas.AnalistaBE[]> GetAllAnalistaAsync() {
            return base.Channel.GetAllAnalistaAsync();
        }
        
        public short GetContarAnalistasXSolicitudes(string strCod, short Est_Solicitud) {
            return base.Channel.GetContarAnalistasXSolicitudes(strCod, Est_Solicitud);
        }
        
        public System.Threading.Tasks.Task<short> GetContarAnalistasXSolicitudesAsync(string strCod, short Est_Solicitud) {
            return base.Channel.GetContarAnalistasXSolicitudesAsync(strCod, Est_Solicitud);
        }
        
        public SolicitudesWEB_GUI.ProxyAnalistas.AnalistaBE GetAnalista(string Id_analista) {
            return base.Channel.GetAnalista(Id_analista);
        }
        
        public System.Threading.Tasks.Task<SolicitudesWEB_GUI.ProxyAnalistas.AnalistaBE> GetAnalistaAsync(string Id_analista) {
            return base.Channel.GetAnalistaAsync(Id_analista);
        }
    }
}
